"""empty message

Revision ID: fadd836fb9b1
Revises: 17c77f7a8860
Create Date: 2020-07-02 20:57:37.131067

"""

import sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fadd836fb9b1'
down_revision = '17c77f7a8860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column('event', 'hide',
                        existing_type=sa.BOOLEAN(),
                        nullable=False)
    except sqlalchemy.exc.OperationalError:
        None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'hide',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###
